# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

constructNet_summary <- function(A, net, samples, rand_sample_no, rand_sample_size, thread_no) {
    .Call(`_SCINET_constructNet_summary`, A, net, samples, rand_sample_no, rand_sample_size, thread_no)
}

constructNet <- function(A, net, samples, thread_no) {
    .Call(`_SCINET_constructNet`, A, net, samples, thread_no)
}

constructNet_crossing <- function(A, net, rows1, samples1, rows2, samples2, rand_sample_no, rand_sample_size, thread_no) {
    .Call(`_SCINET_constructNet_crossing`, A, net, rows1, samples1, rows2, samples2, rand_sample_no, rand_sample_size, thread_no)
}

identifyDiffEdges <- function(mu1, sigma1_sq, n1, mu2, sigma2_sq, n2) {
    .Call(`_SCINET_identifyDiffEdges`, mu1, sigma1_sq, n1, mu2, sigma2_sq, n2)
}

