---
title: "Constructing cell-type-specific networks in human prefrontal cortex"
output: html_notebook
---

## Import libraries
```{r}
library(Matrix)
library(ACTION)
library(igraph)
library(RColorBrewer)
library(ggplot2)
```


## Process expression profile
### Import expression matrix

```{r}
min.cells = 10;

expression = as(readMM('../../input/datasets/HumanBrain/Lake_Fcx_expression.mm'), 'CsparseMatrix')
gene_names = read.table('../../input/datasets/HumanBrain/Lake_Fcx_gene_annotations.txt', as.is = T, header = T)$HGNC
sample_annotations = read.table('../../input/datasets/HumanBrain/Lake_Fcx_sample_annotations.txt', header = T)

filtered_cells = which(sample_annotations$Labels %in% c('End', 'Per'))
sample_annotations = sample_annotations[-filtered_cells, ]
expression = expression[, -filtered_cells]
dim(expression)

d = Matrix::rowSums(expression > 0);
gene.filter.mask = d < min.cells;
sum(gene.filter.mask)
expression = expression[!gene.filter.mask,]
gene_names = gene_names[!gene.filter.mask]

dim(expression)

Labels = sample_annotations$Labels
UL = sort(unique(Labels))
labels = match(Labels, UL)

d = Matrix::colSums(expression)
med = median(d)
D_inv = Diagonal(n = length(d), x = 1 / d)
expression  = expression %*% D_inv # normalize
expression = med*expression # re-scale
expression = log(1 + expression) # variance-stablize (using log-transform)

expression = as(expression, "sparseMatrix") # convert to dgCMatrix format for passing to RCPPArmadillo (in ACTION)
```

### Run ACTION

```{r}
library(ACTION)
reduced_profile = reduce_GeneExpression(expression, PCA_dim=30, iter = 10)
S_r = reduced_profile$cell_signatures
V = reduced_profile$V

ACTION_res = run_ACTION(S_r, k_min=2, k_max = 15, numThreads = 8)
H = ACTION_res$CellProfiles
C = ACTION_res$SmoothingMats;
```


### Impute expression values by regressing over metacells
```{r}
H_stacked = do.call(rbind, H)
C_stacked = do.call(cbind, C)

metagene.metacell = S_r %*% C_stacked
metacell.cell = H_stacked
updated_profiles = refine_solution(S_r, W = metagene.metacell)
C_final = updated_profiles$Refined_C
H_final = updated_profiles$Refined_H

# "Impute" gene expression values
metagene.metacell.final = S_r%*%C_final
gene.metacell.imputed.profile = V%*%metagene.metacell.final
gene.cell.imputed.profile = gene.metacell.imputed.profile %*% H_final

dim(gene.cell.imputed.profile)
```

```{r}


require(BioQC)
require(RNOmni);
require(seriation)
Z = t(apply(gene.cell.imputed.profile, 1, rankNorm));

# D = stats::dist(Z)
# ttt <- hclust(D)
# perm = ttt$order
# X = ttt[perm, ]

row.perm <- seriation::seriate(Z, margin = 1)

OrdRows=as.numeric(row.perm[[1]])
# OrdCols=as.numeric(ttt[[2]])

Z.sorted = Z[OrdRows, ]
save(Z.sorted, file = 'Z_sorted.RData')
save(row.perm, file = 'Z_row_order.RData')

Matrix::image(Z.sorted)

```

## Load PCNet (Parsed from: "Systematic Evaluation of Molecular Networks for Discovery of Disease Genes")

```{r}
load(file = '../../results/Lake_Fcx_mapped_datasets.RData')

net = array(1, c(dim(A)[1], dim(A)[1]))



sample_annotations = read.table('../../input/datasets/HumanBrain/Lake_Fcx_sample_annotations.txt', header = T)
filtered_cells = which(sample_annotations$Labels %in% c('End', 'Per'))
sample_annotations = sample_annotations[-filtered_cells, ]
Labels = sample_annotations$Labels
UL = sort(unique(Labels))
labels = match(Labels, UL)

```

## Use uniform prior, i.e., build over all gene-pairs

```{r}
library(SCINET)
library(R.utils)
# load(file = '../results/Lake_Fcx_mapped_datasets.RData')

mu = vector("list", length(UL))
sigma = vector("list", length(UL))

names(mu) = UL
names(sigma) = UL

for (celltype in UL) {
  printf('%s\n', celltype)
#for (celltype in UL) {
  celltype_samples = which(Labels %in% celltype)
  Net_stats = constructNet(A = as.matrix(A), net=as.matrix(net), samples = celltype_samples, rand_sample_no = 11, rand_sample_size = 30, thread_no = 8)
  mu[[celltype]] = as(Net_stats$mu, 'sparseMatrix');
  sigma[[celltype]] = as(Net_stats$sigma_sq, 'sparseMatrix');
}

save(mu, sigma, file='Brain_networks_uniformPrior.RData)
```

