---
title: "Constructing cell-type-specific networks in human prefrontal cortex"
output: html_notebook
---

## Import libraries
```{r}
library(Matrix)
library(ACTION)
library(igraph)
library(RColorBrewer)
library(ggplot2)
```


## Process expression profile
### Import expression matrix

```{r}
expression = readMM('../../input/datasets/HumanBrain/Lake_Fcx_expression.mm');
gene_names = read.table('../../input/datasets/HumanBrain/Lake_Fcx_gene_annotations.txt', as.is = T, header = T)$HGNC
sample_annotations = read.table('../../input/datasets/HumanBrain/Lake_Fcx_sample_annotations.txt', header = T)

filtered_cells = which(sample_annotations$Labels %in% c('End', 'Per'))
sample_annotations = sample_annotations[-filtered_cells, ]
expression = expression[, -filtered_cells]

Labels = sample_annotations$Labels
UL = sort(unique(Labels))
labels = match(Labels, UL)

d = colSums(expression)
med = median(d)
D_inv = Diagonal(n = length(d), x = 1 / d)
expression  = expression %*% D_inv # normalize
expression = med*expression # re-scale
expression = log(1 + expression) # variance-stablize (using log-transform)

expression = as(expression, "sparseMatrix") # convert to dgCMatrix format for passing to RCPPArmadillo (in ACTION)
```

### Run ACTION

```{r}
library(ACTION)
reduced_profile = reduce_GeneExpression(expression, PCA_dim=30, iter = 10)
S_r = reduced_profile$cell_signatures
V = reduced_profile$V

ACTION_res = run_ACTION(S_r, k_min=2, k_max = 15, numThreads = 8)
H = ACTION_res$CellProfiles
C = ACTION_res$SmoothingMats;
```


### Impute expression values by regressing over metacells
```{r}
H_stacked = do.call(rbind, H)
C_stacked = do.call(cbind, C)

metagene.metacell = S_r %*% C_stacked
metacell.cell = H_stacked
updated_profiles = refine_solution(S_r, W = metagene.metacell)
C_final = updated_profiles$Refined_C
H_final = updated_profiles$Refined_H

# "Impute" gene expression values
metagene.metacell.final = S_r%*%C_final
gene.metacell.imputed.profile = V%*%metagene.metacell.final
gene.cell.imputed.profile = gene.metacell.imputed.profile %*% H_final
```

## Load PCNet (Parsed from: "Systematic Evaluation of Molecular Networks for Discovery of Disease Genes")

```{r}
PCNet = readMM('../../input/networks/PCNet/PCNet.mm')
PCNet_genes = read.csv('../../input/networks/PCNet/PCNet_genes.txt')$Genes
```


## Match network and expression profile
```{r}
# blacklist = c('UBC', 'SUMO1', 'SUMO2', 'SUMO3', gene_names[grep('^RPL|^RPS|^MRP', gene_names)])
blacklist = c('UBC', 'SUMO1', 'SUMO2', 'SUMO3')
common_genes = setdiff(intersect(PCNet_genes, gene_names), blacklist)

order1 = match(common_genes, gene_names)
order2 = match(common_genes, PCNet_genes)

degs = rowSums(PCNet[order2, order2] > 0)
isolated_genes = which(degs == 0)

sample_count = rowSums(gene.cell.imputed.profile[order1,])
missed_genes = which(sample_count == 0);

filtered_genes = union(isolated_genes, missed_genes)

common_genes = common_genes[-filtered_genes]

order1 = match(common_genes, gene_names)
A = as(gene.cell.imputed.profile[order1,], 'sparseMatrix');

order2 = match(common_genes, PCNet_genes)
net = matrix(as.numeric(PCNet[order2, order2] > 0), ncol = length(common_genes))

# save(A, net, common_genes, Labels, file = '../results/Lake_Fcx_mapped_datasets.RData')
dim(net)
dim(A)

A <- as.matrix(A)
```

### Network inference

```{r}
##################################################################################################
library(SCINET)
# load(file = '../results/Lake_Fcx_mapped_datasets.RData')

mu = vector("list", length(UL))
sigma = vector("list", length(UL))

names(mu) = UL
names(sigma) = UL
##################################################################################################
for (celltype in UL[1]) {
#for (celltype in UL) {
  celltype_samples = which(Labels %in% celltype)
  Net_stats = constructNet(A = A, net=net, samples = celltype_samples, rand_sample_no = 100, rand_sample_size = 30, thread_no = 8)
  mu[[celltype]] = as(Net_stats$mu, 'sparseMatrix');
  sigma[[celltype]] = as(Net_stats$sigma_sq, 'sparseMatrix');
}
##################################################################################################
for (celltype in UL) {
  adj = mu[[celltype]];
  adj[is.na(adj)] = 0;
  mu[[celltype]] = adj
  EdgeList = as(adj, 'dgTMatrix')
  EdgeList.df = data.frame(Source=common_genes[EdgeList@i+1], Target=common_genes[EdgeList@j+1], Weight=EdgeList@x)
  EdgeList.df = EdgeList.df[order(EdgeList.df$Weight, decreasing = TRUE),]
  write.table(EdgeList.df, sprintf('../results/networks/%s_net.tsv', celltype), quote = FALSE, col.names = TRUE, row.names = FALSE)
}
#################################################
save(mu, common_genes, file = '../results/networks/Lake_Fcx_networks.RData')
#################################################
```
